### ISSUE TITLE
Idea: option to remove nav_title from the sidebar

### ISSUE THREAD

**Issue by Yura52** [bashtage/sphinx-material#104]
Currently, the title (which is typically something like `f"{project_name} {version}"`) is duplicated in the "header" and TOC.

<img width="777" alt="Screenshot 2021-05-09 at 14 44 43" src="https://user-images.githubusercontent.com/8861742/117570936-28904c00-b0d5-11eb-93c8-cc5322c79fad.png">

Is it possible to add an option that allows to remove the duplication from TOC?

**Comment by bashtage** [comment]
Probably should be easy to do.  Might have side effects though in mobile.

**Comment by bashtage** [comment]
This is not easy because you need it for mobile.  Can be done with some custom CSS.

```css
label.md-nav__title.md-nav__title--site {
	visibility: hidden;
        display: none;
}

@media only screen and (max-width:76.1875em) {
	label.md-nav__title.md-nav__title--site {
		visibility: visible;
                display: block;
	}
}
```

Some other tweaks to CSS might help in this case, but this really is the best solution.
