### ISSUE TITLE
Permalink buttons are invisible

### ISSUE THREAD

**Issue by Yura52** [bashtage/sphinx-material#121]
For some items (from my observations, those are usually API entries automatically generated by Sphinx), the button for getting the permalink is invisible. It is not the case for sphinx-rtd-theme, for example, so I guess it may be a bug.
<img width="1440" alt="Screenshot 2021-10-25 at 21 54 11" src="https://user-images.githubusercontent.com/8861742/138753985-8c8573db-2eed-4db2-ad32-0616e0737a2e.png">

**Comment by Yura52** [comment]
I am not a web developer by any means, but this is my solution

```python
# conf.py
...
html_static_path = ['_static']
html_css_files = ['my_styles.css']
```

```css
/* _static/my_styles.css */

h1 > a.headerlink,
h2 > a.headerlink,
h3 > a.headerlink,
h4 > a.headerlink,
h5 > a.headerlink,
dl.py > dt.sig.sig-object.py a.headerlink {
    /* Example: color: dimgrey !important; */
    color: <your color here> !important;
    display: initial !important;
    transition: initial !important;
}

h1 > a.headerlink:hover,
h2 > a.headerlink:hover,
h3 > a.headerlink:hover,
h4 > a.headerlink:hover,
h5 > a.headerlink:hover,
dl.py > dt.sig.sig-object.py a.headerlink:hover {
    /* Example: color: black !important; */
    color: <your color here> !important;
}

h1:hover > a.headerlink,
h2:hover > a.headerlink,
h3:hover > a.headerlink,
h4:hover > a.headerlink,
h5:hover > a.headerlink,
dl.py > dt.sig.sig-object.py:hover a.headerlink {
    opacity: initial !important;
}
```
