### ISSUE TITLE
Fails to define ordered list classes as sphinx/rst expects

### ISSUE THREAD

**Issue by infinity0** [bashtage/sphinx-material#85]
When parsing rst ordered lists, you can do something like:

~~~~
a. item A
b. item B
~~~~

Either sphinx or docutils is converting this into `<ol class="loweralpha simple">` etc with the list style being applied in `basic.css` by the default theme:

```css
ol.arabic {
    list-style: decimal;
}

ol.loweralpha {
    list-style: lower-alpha;
}

ol.upperalpha {
    list-style: upper-alpha;
}

ol.lowerroman {
    list-style: lower-roman;
}

ol.upperroman {
    list-style: upper-roman;
}
```

sphinx-material does not define these classes however, so these lists should up with roman numerals 1, 2, 3 etc, contradicting the rst source code.

**Comment by infinity0** [comment]
There is also:

```css
.align-left {
    float: left;
}

.align-right {
    float: right;
}
```
