### ISSUE TITLE
Seting custom hex colour for header / links / other components

### ISSUE THREAD

**Issue by axsaucedo** [bashtage/sphinx-material#95]
Before anything thank you for the great project, we have been using this theme for our project now and we have been extremely pleased with the quality/polish (https://kompute.cc). 

Currently the colours provided are quite good, however it would be quite useful if there can be a way to provide a custom HEX to override the colours as opposed to these just being the avialable palettes. Specifically for us, the red goes very well with the theme of the brand of the project, but it does become a bit too much for the eyes. We would be keen to change the tone to make the red darker - we have been refraining ourselves from jumping into the CSS overrides as we wanted to ask here first for both roadmap question and best practice on overriding, as in the ideal world we would also like to take a step further and also have a different colour (non-red) for links.

My questions for this are:
1. Is there currently a way to override these in a modular way?
2. If not, is there a best practice in how this shoudl be done via CSS overrides (eg the relevant classes, etc)
3. are there any plans/ thoughts of making this an extensible feature/

Thank you.

**Comment by axsaucedo** [comment]
I have been able to do this with a relatively simple solution. I think this could be added for people to follow to implement their own themes, and potentially it could even be extended to provide a simple way to enable users to override these high level colours without too much complexity. 

You can find the css override file below - I have replaced the colors with placeholders that can be then replaced with either manually added or dynamic values:

```css
@media (max-width: 1200px) {
.md-header-nav__button {
    color: {{NAV_BUTTON_COLOR}};
    background-color: {{NAV_BUTTON_BG_COLOR}} !important;
    border-radius: 5px;
}
}

h1, h2, h3, h4, h5, h6 {
    color: {{MAIN_TEXT_COLOR}} !important;
}

/* Container backgrounds */
.md-container, .md-main, .md-nav, .md-nav__list {
    background-color: {{MAIN_BG_COLOR}} !important;
    color: {{MAIN_TEXT_COLOR}};
}

.md-header, .md-tabs {
    background-color: {{MAIN_BG_COLOR}} !important;
}

/* Code blocks */
pre, code, .md-source {
    background-color: {{MAIN_CODE_BG_COLOR}} !important;
    color: {{MAIN_CODE_BG_COLOR}} !important;
}

/* All links */
a {
    color: {{MAIN_LINK_COLOR}};
}
a:hover {
    color: {{MAIN_LINK_COLOR_HOVER}};
}

/* Side Menu Links */
.md-nav__item a {
    color: {{SIDE_MENU_LINK_COLOR}};
}
.md-nav__item a:hover {
    color: {{SIDE_MENU_LINK_COLOR_HOVER}};
}
```
